"""Approved public Help / FAQ copy (build/help.html, client-approved) and the
member educational lines the application prints. Generated from the approved
prototype on 19 Sep 2026; the seed loads it once and never overwrites edits."""

HELP_FAQ = [
    {"key": 'what_is_veye', "category": 'About Veye', "title": 'What is Veye?', "body": 'Veye programs help members manage disease, lose weight and take a proactive role in their own healthcare. Veye takes a nutritional approach to family health. Whether challenged by diabetes, heart disease, osteoporosis, infertility, asthma or the simple desire to improve quality of life, Veye will be there to offer detailed nutritional planning and day-to-day support. Veye makes it possible to put medical advice into action.', "display_order": 1},
    {"key": 'what_subscription_am_i_on', "category": 'Subscription and My Account', "title": 'What subscription am I on?', "body": 'Create an account to see the subscription options.', "display_order": 2},
    {"key": 'how_do_i_use_the_veye_site', "category": 'Using the Platform', "title": 'How do I use the Veye site?', "body": 'The Veye site is designed to be simple and easy to use. Veye uses an internal AI assistant to guide you at your pace, concentrate on the things that work best for you, and give you personalized tips and advice. You can start with a question to the Veye Companion, randomly click on the features that interest you, or go to the left column and take the time to set up your program.', "display_order": 3},
    {"key": 'where_should_i_start', "category": 'Using the Platform', "title": 'Where should I start?', "body": 'For best results, after you sign in Veye suggests that you start by filling in the sections on the left in order. Create a baseline assessment by filling in a Progress Tracker of your choice, or filling in more than one. Try using the Mood Tracker, eventually understanding how food affects your mood.', "display_order": 4},
    {"key": 'i_can_t_sign_in_to_my_account', "category": 'Technical Issues', "title": 'I can’t sign in to my account', "body": 'Check that you are using the email address you signed up with, and that Caps Lock is off. If you are still unable to sign in, close the tab and open Veye again before trying once more.', "display_order": 5},
    {"key": 'i_forgot_my_password', "category": 'Technical Issues', "title": 'I forgot my password', "body": 'Use the show/hide control in the password field to confirm what you have typed. Password resets will be available from the sign-in screen; until then, email us and we will help you back in.', "display_order": 6},
    {"key": 'a_page_will_not_load_or_looks_broken', "category": 'Technical Issues', "title": 'A page will not load or looks broken', "body": 'Refresh the page first. If that does not help, clear your browser cache and reload. A stale cached file is the most common cause of a page rendering incorrectly.', "display_order": 7},
    {"key": 'what_is_metabolism', "category": 'Diet and Nutrition Terminology', "title": 'What is metabolism?', "body": 'Your metabolism is how you process and convert energy, and is controlled by AMPK. Metabolism controls your weight, mental focus, physical performance, how you age, and more. By following the Veye program you can control AMPK, and therefore your metabolism.', "display_order": 8},
    {"key": 'is_intermittent_fasting_good_for_you', "category": 'Diet and Nutrition Terminology', "title": 'Is intermittent fasting good for you?', "body": 'Although intermittent fasting has shown promise in reducing senescent, or “zombie” cells, you can achieve the same effect without starving by eating a low calorie diet with the proper ratio of macronutrients. The Veye program restricts calories without sacrifice.', "display_order": 9},
    {"key": 'why_do_i_need_to_eat_protein_at_every_meal', "category": 'Diet and Nutrition Terminology', "title": 'Why do I need to eat protein at every meal?', "body": 'To activate glucagon and AMPK, two important components to health.', "display_order": 10},
    {"key": 'how_much_protein_do_i_need', "category": 'Diet and Nutrition Terminology', "title": 'How much protein do I need?', "body": 'Most women need 77grams per day and men 121grams, although this varies by the individual. The Veye program can help you determine your exact protein needs.', "display_order": 11},
    {"key": 'how_is_veye_different_from_other_diet_programs', "category": 'About Veye', "title": 'How is Veye different from other diet programs?', "body": 'Veye goes far beyond what diet sites such as WW (Weight Watchers), Noom and Jenny Craig offer, and beyond what most nutritionists offer. Veye’s proprietary systems are about more than weight loss — they are about improved health. The Veye nutritional program is based on peer reviewed and published Medical research. Veye maintains relationships with medical organizations, cutting edge thinkers, and sole practitioners.', "display_order": 12},
    {"key": 'what_is_in_my_account', "category": 'Subscription and My Account', "title": 'What is in My Account?', "body": 'To recover your account, go to the sign in section, enter your email and reset your password.', "display_order": 13},
    {"key": 'how_do_i_set_up_my_meals', "category": 'Using the Platform', "title": 'How do I set up my meals?', "body": 'Then make your food choices — this will help the Veye Companion customize your meals. After you have chosen the foods you like to eat, go to Your Days and the Veye Companion will help you create meals that work around your lifestyle, not the other way around. Before you start, the Veye Companion will give you the opportunity to explore the science behind our program.', "display_order": 14},
    {"key": 'what_should_i_do_every_day', "category": 'Using the Platform', "title": 'What should I do every day?', "body": 'Finally, fill out the food diary as often as possible. The Veye Companion will assess your choices and let you know what meals are perfect for you, and what can be improved.', "display_order": 15},
    {"key": 'my_progress_does_not_seem_to_be_saving', "category": 'Technical Issues', "title": 'My progress does not seem to be saving', "body": 'Make sure you press Save on the screen you are filling in, and that your browser is not in private/incognito mode, which discards stored progress when the window closes.', "display_order": 16},
    {"key": 'which_browsers_and_devices_does_veye_support', "category": 'Technical Issues', "title": 'Which browsers and devices does Veye support?', "body": 'Veye works on current versions of Chrome, Edge, Firefox and Safari, on desktop, tablet and phone. If you are on an older browser, updating it usually resolves display problems.', "display_order": 17},
    {"key": 'my_issue_is_still_not_fixed', "category": 'Technical Issues', "title": 'My issue is still not fixed', "body": 'Email help@veye.co with a short description of what happened and which page you were on, and we will take it from there.', "display_order": 18},
    {"key": 'what_is_the_key_to_living_longer', "category": 'Diet and Nutrition Terminology', "title": 'What is the key to living longer?', "body": 'Calorie restriction is the only known way to increase longevity. The Veye program allows calorie restriction without hunger or deprivation.', "display_order": 19},
    {"key": 'is_a_vegan_diet_the_best_one', "category": 'Diet and Nutrition Terminology', "title": 'Is a vegan diet the best one?', "body": 'The research is inconclusive, although Veye respects individuals who choose this lifestyle. It is hard to get adequate protein on a vegan diet. Veye can help you maintain a vegan diet, or make healthy choices whatever your dietary preference is.', "display_order": 20},
    {"key": 'can_you_eat_too_much_protein', "category": 'Diet and Nutrition Terminology', "title": 'Can you eat too much protein?', "body": 'Yes, it is important to have the right protein prescription for you and your lifestyle. Veye will give you your protein requirement and help you maintain lean muscle mass.', "display_order": 21},
    {"key": 'is_there_protein_in_cantaloupe_broccoli', "category": 'Diet and Nutrition Terminology', "title": 'Is there protein in cantaloupe, broccoli?', "body": 'Although there may be trace amounts, there is not enough to activate glucagon or AMPK, and therefore these are not good protein sources.', "display_order": 22},
]

MEMBER_COPY = [
    {"key": "companion_first_visit_welcome", "title": "Companion — first visit welcome", "display_order": 1,
     "body": "Welcome to the Veye program — I look forward to working with you. How would you like to begin? I can start with the why to — the reasons behind the program and its basics — or go straight to the how to and begin meal planning."},
    {"key": "companion_returning_welcome", "title": "Companion — returning welcome", "display_order": 2,
     "body": "Welcome back — I'm Sprout, your Veye companion. What would you like to work on today?"},
    {"key": "health_assessment_parameters_note", "title": "Health Assessment — under the result", "display_order": 3,
     "body": "These parameters reflect the overall inflammation in your organs. Your goal is to keep inflammation in control — not too much or too little. Symptoms of chronic diseases are associated with chronic high inflammation."},
    {"key": "simple_quiz_intro", "title": "Simple Quiz — introduction", "display_order": 4,
     "body": "8 yes/no questions to track your progress. Best health is 8 \"No\" answers."},
    {"key": "daily_health_tip", "title": "Dashboard — Daily Health tip", "display_order": 0, "status": "Draft",
     "body": "Write the daily tip members should see on their dashboard, then publish it. The prototype's sample sentence "
             "(\"Although you are in moderately good health…\") was placeholder copy and is not shown to members."},
    {"key": "development_section_note", "title": "Development sections — status line", "display_order": 5,
     "body": "Under development — more coming."},
]
